isEnabled = true
backgroundColor = 926762943
pressedBackgroundColor = 926762823
keyColor = -1
pressedKeyColor = -16777216
rainbowMode = false
rainbowOffset = 9
rainbowSpeed = 4
roundedBackground = true
renderInGui = true
keyShadow = false
cpsType = "ALWAYS"
displayFactor = 1.0
horizontalSlider = 1032
verticalSlider = 642
showMovement = true
showJump = true
showClick = true
